# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

# ================================
# 1. CLASSE DO RECOMENDADOR
# ================================
class RecomendadorFilmes:
    def __init__(self, caminho_arquivo):
        """
        Inicializa o sistema de recomendação:
        - Carrega os dados
        - Limpa e prepara
        - Cria matriz TF-IDF
        - Calcula similaridade
        """

        try:
            self.df = pd.read_csv(
                caminho_arquivo,
                delimiter=',',
                encoding='utf-8',
                engine='python',
                on_bad_lines='skip'
            )
            print("Base de dados carregada com sucesso!")
        except Exception as e:
            print(f"Erro ao carregar a base: {e}")
            exit()

        # ================================
        # 2. LIMPEZA E PREPARAÇÃO
        # ================================

        print(f"\nLinhas: {self.df.shape[0]}")
        print(f"Colunas: {self.df.shape[1]}")

        # Seleciona apenas colunas relevantes
        self.df = self.df[['original_title', 'overview']]

        # Remove linhas com sinopse nula
        self.df = self.df.dropna(subset=['overview']).reset_index(drop=True)

        # Normaliza títulos (minúsculo + remove espaços)
        self.df['original_title_clean'] = self.df['original_title'].str.lower().str.strip()

        # ================================
        # 3. FEATURE ENGINEERING
        # ================================

        # Aqui você pode adicionar mais informações no futuro (gênero, elenco etc.)
        self.df['content'] = self.df['overview']

        # ================================
        # 4. TF-IDF MELHORADO
        # ================================

        self.tfidf = TfidfVectorizer(
            stop_words='english',
            ngram_range=(1, 2),  # palavras + combinações
            max_df=0.8,          # ignora palavras muito frequentes
            min_df=5             # ignora palavras raras
        )

        # Cria matriz de features
        self.tfidf_matrix = self.tfidf.fit_transform(self.df['content'])

        # ================================
        # 5. SIMILARIDADE (OTIMIZADA)
        # ================================

        # Mais rápido que cosine_similarity
        self.cosine_sim = linear_kernel(self.tfidf_matrix, self.tfidf_matrix)

        # Mapeamento de título → índice
        self.indices = pd.Series(
            self.df.index,
            index=self.df['original_title_clean']
        ).drop_duplicates()

    # ================================
    # 6. FUNÇÃO DE RECOMENDAÇÃO
    # ================================
    def recomendar(self, titulo, top_n=5):
        """
        Retorna uma lista de filmes similares com base na sinopse
        """

        # Normaliza entrada do usuário
        titulo = titulo.lower().strip()

        # Verifica se o filme existe
        if titulo not in self.indices:
            print(f"Filme '{titulo}' não encontrado na base.")
            return []

        idx = self.indices[titulo]

        # Calcula similaridade com todos os filmes
        sim_scores = list(enumerate(self.cosine_sim[idx]))

        # Ordena pelos mais similares
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

        # Remove o próprio filme (posição 0)
        sim_scores = sim_scores[1:top_n + 1]

        movie_indices = [i[0] for i in sim_scores]

        # ================================
        # 7. OUTPUT MELHORADO
        # ================================
        recomendacoes = []

        print(f"\nFilmes recomendados para '{titulo}':\n")

        for i, idx in enumerate(movie_indices, start=1):
            titulo_filme = self.df['original_title'].iloc[idx]
            overview = self.df['overview'].iloc[idx]

            print(f"{i}. {titulo_filme}")
            print(f"   {overview[:120]}...\n")

            recomendacoes.append(titulo_filme)

        return recomendacoes

# ================================
# 8. EXECUÇÃO
# ================================
if __name__ == "__main__":

    caminho = r'/content/Top_10000_Movies.csv'

    # Inicializa o recomendador
    sistema = RecomendadorFilmes(caminho)

    # Input do usuário
    filme = input("\nDigite o nome do filme: ")

    # Gera recomendações
    sistema.recomendar(filme, top_n=5)